In [3]:
import torch, math

def delta_a(x, offset, magnitute=0):
    if type(x) is not torch.Tensor:
        x = torch.tensor(x)
    if type(offset) is not torch.Tensor:
        offset = torch.tensor(offset)

    pi = torch.tensor(math.pi)

    a = torch.tensor(1/10.0)
    
    # return (1/ ( a.abs() * pi.sqrt())) * torch.exp(-((x / a) ** 2))
    dja = ((1 / (a.abs() * pi.sqrt())) * torch.exp(-(((x - offset) / a) ** 2))).round()
    dja = dja / 6 * magnitute
    return dja


input = torch.tensor([0, 1.0, 2.0, 3.0, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

print(input)

magnitude = torch.tensor(
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
)

def func(x, magnitude):
    if type(x) is not torch.Tensor:
        x = torch.tensor(x)
    if type(magnitude) is not torch.Tensor:
        magnitude = torch.tensor(magnitude)
    
    x.round_().clip_(0, 15)
    
    return (
        delta_a(x, 0,  magnitude[0]) +
        delta_a(x, 1,  magnitude[1]) +
        delta_a(x, 2,  magnitude[2]) +
        delta_a(x, 3,  magnitude[3]) +
        delta_a(x, 4,  magnitude[4]) +
        delta_a(x, 5,  magnitude[5]) +
        delta_a(x, 6,  magnitude[6]) +
        delta_a(x, 7,  magnitude[7]) +
        delta_a(x, 8,  magnitude[8]) +
        delta_a(x, 9,  magnitude[9]) +
        delta_a(x, 10, magnitude[10]) +
        delta_a(x, 11, magnitude[11]) +
        delta_a(x, 12, magnitude[12]) +
        delta_a(x, 13, magnitude[13]) +
        delta_a(x, 14, magnitude[14]) +
        delta_a(x, 15, magnitude[15]) 
    )


print(func(input, magnitude))

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15.])
tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15.])


In [4]:
qq = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], dtype=torch.float32)

dja = math.sqrt(2)**-qq 


print(dja)

tensor([1.0000, 0.7071, 0.5000, 0.3536, 0.2500, 0.1768, 0.1250, 0.0884, 0.0625,
        0.0442, 0.0313, 0.0221, 0.0156, 0.0110, 0.0078, 0.0055])


In [5]:
# def _dirac_delta(self, x, offset, magnitute):

#     return torch.where(x == offset, magnitute, torch.tensor(0.0))
#     # pi = torch.tensor(math.pi)
#     # a = torch.tensor(1 / 10.0)

#     # dja = (
#     #     (1 / (a.abs() * pi.sqrt())) * torch.exp(-(((x - offset) / a) ** 2))
#     # ).round()
#     # dja = dja / 6 * magnitute
#     # return dja

# def _f_map(self, x_q):
#     assert 0 <= x_q.min() and x_q.max() <= self.n_levels, f"{x_q.unique()}"

#     _f_y = torch.zeros_like(x_q)
#     mag = round_ste.apply(self.magnitude.clamp(0, 255))
#     for i in range(self.n_levels):
#         dja = self._dirac_delta(x_q, i, mag[i])
#         # print(dja.requires_grad)
#         _f_y = _f_y + round_ste.apply(dja)
#     return _f_y

In [6]:
import math

# Given number
# num = 65535

def int_log(num):
    # Initialize the logarithm result
    log2_approx = 0

    # Shift right until the number becomes 1
    while num > 1:
        num >>= 1  # Right shift by 1 bit (equivalent to dividing by 2)
        log2_approx += 1
    return log2_approx

print(int_log(127))
print(int_log(128))
print(int_log(129))

6
7
7


In [7]:
-int_log(64464)

-15

In [8]:
import torch
x = torch.linspace(0, 65535, 65536, dtype=torch.int32)


print(x)
print(x.log2().clamp(0, 20).unique().numel())
print(x.log2().round().clamp(0, 20).unique().numel())

tensor([    0,     1,     2,  ..., 65533, 65534, 65535], dtype=torch.int32)
65535
17


In [9]:
dja = -x.log2().round()*2**16+2**20
print(dja)
print(dja.unique().numel(), dja.unique())
wns = (dja / 2**16).round()
print(wns)



print(wns.unique().numel(), wns.unique())


tensor([     inf, 1048576.,  983040.,  ...,       0.,       0.,       0.])
18 tensor([      0.,   65536.,  131072.,  196608.,  262144.,  327680.,  393216.,
         458752.,  524288.,  589824.,  655360.,  720896.,  786432.,  851968.,
         917504.,  983040., 1048576.,      inf])
tensor([inf, 16., 15.,  ...,  0.,  0.,  0.])
18 tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., inf])


In [10]:
2**wns

tensor([       inf, 6.5536e+04, 3.2768e+04,  ..., 1.0000e+00, 1.0000e+00,
        1.0000e+00])

In [11]:
dja = torch.tensor([0.0,0.001,0.005,0.01,0.02,0.03,0.04,0.05,0.1,0.2,0.5,1.0]) * 2**16

print(dja)

tensor([    0.0000,    65.5360,   327.6800,   655.3600,  1310.7200,  1966.0800,
         2621.4399,  3276.8000,  6553.6001, 13107.2002, 32768.0000, 65536.0000])
