In [46]:
import torch, math

def delta_a(x, offset, magnitute=0):
    if type(x) is not torch.Tensor:
        x = torch.tensor(x)
    if type(offset) is not torch.Tensor:
        offset = torch.tensor(offset)

    pi = torch.tensor(math.pi)

    a = torch.tensor(1/10.0)
    
    # return (1/ ( a.abs() * pi.sqrt())) * torch.exp(-((x / a) ** 2))
    dja = ((1 / (a.abs() * pi.sqrt())) * torch.exp(-(((x - offset) / a) ** 2))).round()
    dja = dja / 6 * magnitute
    return dja


input = torch.tensor([0, 1.0, 2.0, 3.0, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

print(input)

magnitude = torch.tensor(
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
)

def func(x, magnitude):
    if type(x) is not torch.Tensor:
        x = torch.tensor(x)
    if type(magnitude) is not torch.Tensor:
        magnitude = torch.tensor(magnitude)
    
    x.round_().clip_(0, 15)
    
    return (
        delta_a(x, 0,  magnitude[0]) +
        delta_a(x, 1,  magnitude[1]) +
        delta_a(x, 2,  magnitude[2]) +
        delta_a(x, 3,  magnitude[3]) +
        delta_a(x, 4,  magnitude[4]) +
        delta_a(x, 5,  magnitude[5]) +
        delta_a(x, 6,  magnitude[6]) +
        delta_a(x, 7,  magnitude[7]) +
        delta_a(x, 8,  magnitude[8]) +
        delta_a(x, 9,  magnitude[9]) +
        delta_a(x, 10, magnitude[10]) +
        delta_a(x, 11, magnitude[11]) +
        delta_a(x, 12, magnitude[12]) +
        delta_a(x, 13, magnitude[13]) +
        delta_a(x, 14, magnitude[14]) +
        delta_a(x, 15, magnitude[15]) 
    )


print(func(input, magnitude))

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15.])
tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15.])


In [47]:
qq = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], dtype=torch.float32)

dja = math.sqrt(2)**-qq 


print(dja)

tensor([1.0000, 0.7071, 0.5000, 0.3536, 0.2500, 0.1768, 0.1250, 0.0884, 0.0625,
        0.0442, 0.0313, 0.0221, 0.0156, 0.0110, 0.0078, 0.0055])


In [48]:
# def _dirac_delta(self, x, offset, magnitute):

#     return torch.where(x == offset, magnitute, torch.tensor(0.0))
#     # pi = torch.tensor(math.pi)
#     # a = torch.tensor(1 / 10.0)

#     # dja = (
#     #     (1 / (a.abs() * pi.sqrt())) * torch.exp(-(((x - offset) / a) ** 2))
#     # ).round()
#     # dja = dja / 6 * magnitute
#     # return dja

# def _f_map(self, x_q):
#     assert 0 <= x_q.min() and x_q.max() <= self.n_levels, f"{x_q.unique()}"

#     _f_y = torch.zeros_like(x_q)
#     mag = round_ste.apply(self.magnitude.clamp(0, 255))
#     for i in range(self.n_levels):
#         dja = self._dirac_delta(x_q, i, mag[i])
#         # print(dja.requires_grad)
#         _f_y = _f_y + round_ste.apply(dja)
#     return _f_y

In [49]:
import math

# Given number
# num = 65535

def int_log(num):
    # Initialize the logarithm result
    log2_approx = 0

    # Shift right until the number becomes 1
    while num > 1:
        num >>= 1  # Right shift by 1 bit (equivalent to dividing by 2)
        log2_approx += 1
    return log2_approx

print(int_log(127))
print(int_log(128))
print(int_log(129))

6
7
7


In [50]:
-int_log(64464)

-15

In [51]:
import torch
x = torch.linspace(0, 65535, 65536, dtype=torch.int32)


print(x)
print(x.log2().clamp(0, 20).unique().numel())
print(x.log2().round().clamp(0, 20).unique().numel())

tensor([    0,     1,     2,  ..., 65533, 65534, 65535], dtype=torch.int32)
65535
17


In [52]:
dja = -x.log2().round()*2**16+2**20
print(dja)
print(dja.unique().numel(), dja.unique())
wns = (dja / 2**16).round()
print(wns)



print(wns.unique().numel(), wns.unique())


tensor([     inf, 1048576.,  983040.,  ...,       0.,       0.,       0.])
18 tensor([      0.,   65536.,  131072.,  196608.,  262144.,  327680.,  393216.,
         458752.,  524288.,  589824.,  655360.,  720896.,  786432.,  851968.,
         917504.,  983040., 1048576.,      inf])
tensor([inf, 16., 15.,  ...,  0.,  0.,  0.])
18 tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., inf])


In [53]:
2**wns

tensor([       inf, 6.5536e+04, 3.2768e+04,  ..., 1.0000e+00, 1.0000e+00,
        1.0000e+00])

In [54]:
dja = torch.tensor([0.0,0.001,0.005,0.01,0.02,0.03,0.04,0.05,0.1,0.2,0.5,1.0]) * 2**16

print(dja)

tensor([    0.0000,    65.5360,   327.6800,   655.3600,  1310.7200,  1966.0800,
         2621.4399,  3276.8000,  6553.6001, 13107.2002, 32768.0000, 65536.0000])


In [111]:
import torch


def bits_required(x_int):
    # 절대값을 취하고 이진수 변환 후, 부호 비트 포함해서 비트 수 계산
    _ones = torch.zeros_like(x_int)
    
    out = torch.where(x_int == 0, _ones, x_int)
    
    return (
        len(bin(abs(x_int))) - 2 + 1
    )  # bin()은 '0b'로 시작하기 때문에 -2, 부호 비트 포함


def log2_fixed_point(x):
    # UINT16 입력값을 정수형으로 변환
    x = x.to(torch.int32)

    # x가 0인 경우를 처리하기 위해 결과를 미리 -1로 초기화합니다.
    log2_int = torch.full_like(x, -1, dtype=torch.int32)
    # dja = bits_required(x)
    # print(dja)
    # 1. log2의 정수 부분 계산
    temp_x = x.clone()
    for i in range(15, -1, -1):
        shift = 1 << i
        greater_equal = temp_x >= shift
        log2_int += greater_equal.to(torch.int32)
        temp_x = temp_x >> greater_equal.to(torch.int32)
    # print(log2_int)
    # 2. 소수점 아래 한 자리 계산 (0.1, 0.2, ..., 0.9를 정수로 근사)
    # 0.1 ~ 0.9에 해당하는 상수 값을 정수로 표현
    fractional_add = torch.zeros_like(x, dtype=torch.int32)

    # 0.5 추가 (0.1 * 5)
    temp_x = x - (1 << log2_int)
    temp_x = temp_x << 1  # temp_x *= 2
    fractional_add += (temp_x >= (1 << log2_int)).to(torch.int32) * 5

    # # 0.2 추가 (0.1 * 2)
    # temp_x = x - (1 << log2_int) - (fractional_add >> 1)
    # temp_x = temp_x << 2  # temp_x *= 4
    # fractional_add += (temp_x >= (1 << log2_int)).to(torch.int32) * 2

    # # 0.1 추가
    # temp_x = x - (1 << log2_int) - ((fractional_add * 3) >> 2)
    # temp_x = temp_x << 3  # temp_x *= 8
    # fractional_add += (temp_x >= (1 << log2_int)).to(torch.int32) * 1

    # 최종 log2 값은 정수 부분과 fractional_add를 합친 것입니다.
    return log2_int * 10 + fractional_add


# 예시 UINT16 입력값
# x = torch.tensor([1, 2, 4, 8, 16, 32, 65535], dtype=torch.int32)

# # log2 값을 소수점 아래 1자리까지 계산
# log2_values = log2_fixed_point(x)

# # 결과 출력 (소수점 아래 1자리까지 표현된 결과)
# print(
#     log2_values
# )  # 예시 출력: 0, 10, 20, 30, 40, 50, 1590 (각각 0.0, 1.0, 2.0, ...를 의미)


dja = torch.randint(1, 65535, (12, 12, 197, 197), dtype=torch.int32)
# dja = log2_fixed_point(dja)
# print(dja.unique())

count = 10
import time
start = time.time()
for _ in range(count):
    dd = log2_fixed_point(dja)
print((time.time()-start)/count)
print(dd.unique(), dd.unique().numel())

start = time.time()
for _ in range(count):
    dd = (dja.log2()*2).floor()/2

print((time.time()-start)/count)
print(dd.unique(), dd.unique().numel())

0.1700700044631958
tensor([  0,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
         75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130, 135, 140,
        145, 150, 155], dtype=torch.int32) 31
0.009419822692871093
tensor([ 0.0000,  1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,
         4.5000,  5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,  8.0000,
         8.5000,  9.0000,  9.5000, 10.0000, 10.5000, 11.0000, 11.5000, 12.0000,
        12.5000, 13.0000, 13.5000, 14.0000, 14.5000, 15.0000, 15.5000]) 31


In [115]:
import torch
import numpy as np


def histogram_equalization(x):
    # 1. 데이터 정규화 (0에서 1 사이로)
    x = x.float()
    x = x / x.max()

    # 2. 히스토그램 계산
    hist = torch.histc(x, bins=256, min=0.0, max=1.0)

    # 3. 누적 분포 함수 (CDF) 계산
    cdf = torch.cumsum(hist, dim=0)
    cdf = cdf / cdf[-1]  # 정규화

    # 4. 평활화된 값으로 매핑
    x_eq = cdf[(x * 255).long()]

    # 5. 스케일링 및 반올림
    x_eq = (x_eq * 255).round().long()

    return x_eq


# 예시 데이터 (0에서 65535 사이의 값)
original_vector = torch.randint(0, 65536, (16,), dtype=torch.int)

# 1. 데이터 스케일링 (0에서 1 사이로 변환)
scaled_vector = original_vector / 65535.0

# 2. 히스토그램 평활화 적용
equalized_vector = histogram_equalization(scaled_vector)

print("Original Vector: ", original_vector)
print("Scaled Vector: ", scaled_vector)
print("Equalized Vector: ", equalized_vector)
print(torch.norm(equalized_vector * 255 - original_vector.float()))

Original Vector:  tensor([22795, 33580, 31684, 19488, 52828,   529, 47507,  5399, 38164, 55405,
        25918, 24116, 30144, 65166, 21876, 37292], dtype=torch.int32)
Scaled Vector:  tensor([0.3478, 0.5124, 0.4835, 0.2974, 0.8061, 0.0081, 0.7249, 0.0824, 0.5823,
        0.8454, 0.3955, 0.3680, 0.4600, 0.9944, 0.3338, 0.5690])
Equalized Vector:  tensor([ 80, 159, 128,  48, 207,  16, 191,  32, 191, 223, 112,  96, 112, 255,
         64, 159])
tensor(17137.7207)
